name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACKS_USERNAME: ${{secrets.BROWSERSTACKS_USERNAME}}
            BROWSERSTACKS_KEY: ${{secrets.BROWSERSTACKS_KEY}}
            BROWSERSTACKS_APP_ID: ${{secrets.BROWSERSTACKS_APP_ID}}

            
          run: npm run wdio:bs:purchase
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
